### ISSUE TITLE
"Less than" comparison is highlighted as dom tag.

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-jsx.tmbundle#15]
"Less than" comparison is highlighted as dom tag.

![image](https://cloud.githubusercontent.com/assets/351038/18547042/aac35f10-7b41-11e6-8150-fdf0286e3369.png)

**Comment by jjeising** [comment]
This is a known issue (#9). There currently is no easy fix on the parser as the regex parser has very little context.

You can work around this by using spaces between operator and variables.
