### ISSUE TITLE
When import line has comment at end, highlighting of next line breaks.

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-jsx.tmbundle#20]
The `import` statement on the second line is not highlighted in red.

![image](https://cloud.githubusercontent.com/assets/351038/20095177/bedfa25a-a5a4-11e6-8b37-1aabc935e7bd.png)

**Comment by jjeising** [comment]
Is it possible that this is an error in the original Javascript bundle? I still get this without an injection.

**Comment by koenpunt** [comment]
Ah yes of course, wrong repo

**Comment by jjeising** [comment]
No problem, thanks nonetheless for other reports 🙂
