### ISSUE TITLE
Bundle doesn't appear in textmate

### ISSUE THREAD

**Issue by hryamzik** [jjeising/javascript-jsx.tmbundle#21]
That's a bit confusing as TextMate does see the bundle:

![image](https://cloud.githubusercontent.com/assets/1643962/21197514/04383f8e-c23c-11e6-9b97-adeec736cf42.png)
![image](https://cloud.githubusercontent.com/assets/1643962/21197567/2fe0c9d0-c23c-11e6-8aba-e10652f74412.png)

Do I miss something at this point?

**Comment by jjeising** [comment]
It seems like textmate currently lists bundles from the official repository in this list. I can reproduce this for other installed bundles. I don't think I can do anything about this.

(Looks like you also have the "Themes" filter enabled, which limits results)

**Comment by hryamzik** [comment]
@jjeising tried with all the lists, no luck. Any ideas how to enable this bundle?

![image](https://cloud.githubusercontent.com/assets/1643962/21224158/04aa6070-c2cb-11e6-8781-d90b8c48ed51.png)

**Comment by jjeising** [comment]
It is enabled and automatically injected in all JavaScript contents.

You can check this in the bundle editor here:

![jsx_bundle](https://cloud.githubusercontent.com/assets/40333/21226069/389fd596-c2d4-11e6-9317-b718ff049656.png)

Maybe I should note this in the README.
