### ISSUE TITLE
Closing script tag in html page doesn't end scope

### ISSUE THREAD

**Issue by koenpunt** [jjeising/javascript-jsx.tmbundle#8]
With react bundle enabled:

![image](https://cloud.githubusercontent.com/assets/351038/17664217/dba39d28-62f2-11e6-93ad-3479b2203e9c.png)

Without react bundle enabled:

![image](https://cloud.githubusercontent.com/assets/351038/17664240/f5409b00-62f2-11e6-86a0-739d968e9dc6.png)

**Comment by jjeising** [comment]
This should be fixed with b39e4a5. I've tested this with the HTML and Ruby ERB bundles.

**Comment by koenpunt** [comment]
Great, that does it indeed, thanks!
